"""Load the bundled Copperline CSVs into typed structures.

All three CSVs in /data are synthetic (generated by generate_data.py). There is no
uploader and no integration: the app reads these files and nothing else.
"""
from __future__ import annotations

import os
from functools import lru_cache

import pandas as pd

DATA_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), "data")


def _coerce(value: str):
    """CSV values arrive as strings; turn the numeric ones into floats."""
    try:
        return float(value)
    except (TypeError, ValueError):
        return value


@lru_cache(maxsize=1)
def load_actuals() -> pd.DataFrame:
    df = pd.read_csv(os.path.join(DATA_DIR, "copperline_actuals.csv"))
    df["month"] = df["month"].astype(str)
    return df


@lru_cache(maxsize=1)
def load_assumptions() -> dict:
    df = pd.read_csv(os.path.join(DATA_DIR, "copperline_assumptions.csv"))
    return {row["assumption"]: _coerce(row["value"]) for _, row in df.iterrows()}


@lru_cache(maxsize=1)
def load_assumption_notes() -> dict:
    df = pd.read_csv(os.path.join(DATA_DIR, "copperline_assumptions.csv"))
    return {row["assumption"]: row["note"] for _, row in df.iterrows()}


@lru_cache(maxsize=1)
def load_target() -> dict:
    df = pd.read_csv(os.path.join(DATA_DIR, "copperline_acquisition_target.csv"))
    return {row["field"]: _coerce(row["value"]) for _, row in df.iterrows()}
